@startuml
actor 演员
boundary 边界
control 控制
entity 实体
database 数据库
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml